@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

SET ERROR_CODE=%~1 
SET ERROR_CODE=!ERROR_CODE: =!
IF "!ERROR_CODE!"=="" SET ERROR_CODE=1 

SHIFT 
SET ERROR_MESSAGE="
FOR /F "tokens=1,* delims= " %%A IN ("%*") DO (
  SET NEXT=%%~B
  IF "!NEXT!" NEQ "" (
    IF "!ERROR_MESSAGE!"=="""" (
      SET ERROR_MESSAGE=!NEXT!
    ) ELSE (
      SET ERROR_MESSAGE=!ERROR_MESSAGE!^ !NEXT!
      SET ERROR_MESSAGE=!ERROR_MESSAGE!
    )
  )
)
SET ERROR_MESSAGE=!ERROR_MESSAGE!

IF !ERROR_MESSAGE!=="" ( 
  SET ERROR_MESSAGE="It did not work." 
)


SET NaN=
SET "NaN="&FOR /F "DELIMS=0123456789" %%A IN ("!ERROR_CODE!") DO SET NaN=%%A
IF DEFINED NaN (
  IF "!NaN: =!" NEQ "" (
    SET ERROR_MESSAGE=!ERROR_CODE: =! !ERROR_MESSAGE:"=!
  )
  SET ERROR_CODE=1
)

SET OUTPUT=
FOR /F "USEBACKQ TOKENS=*" %%A IN (`ECHO   !ERROR_MESSAGE! `) DO (SET OUTPUT=%%~A )
>&2 ECHO ERROR !ERROR_CODE!: !OUTPUT!
EXIT /b %ERROR_CODE%
